import { GetServerSideProps } from "next";
import Header from "@/components/Header";
import Head from "next/head";
import { getCollection } from "@/utils/mongo-db/db-client";
import { ObjectId } from "mongodb";
import { UserDTO } from "@/types/user";
import { buildUserDTOFromDocument } from "@/utils/transformer/documentToDTO";
import FavoriteMain from "@/components/FavoriteMain";

export default function Favorites({ user }: { user: UserDTO }) {
  return (
    <>
      <Head>
        <title>Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <FavoriteMain user={user} />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const userId = req.cookies.user;
  if (!userId) {
    return { redirect: { destination: "/signup", permanent: false } };
  }
  const collection = await getCollection();

  const user = await collection.findOne({ _id: new ObjectId(userId) });
  if (!user) {
    return { redirect: { destination: "/signup", permanent: false } };
  }
  return {
    props: {
      user: buildUserDTOFromDocument(user),
    },
  };
};
