import Head from "next/head";
import Header from "@/components/Header";
import styles from "@/styles/About.module.css";
import Background from "@/components/Background";

export default function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.aboutDiv}></div>
      <Background />
    </>
  );
}
