import Head from "next/head";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { Recipe } from "@/types/recipes";
import RecipeList from "@/components/RecipeList";
import Header from "@/components/Header";
import { getRecipes } from "@/util/api-client";

export default function HomePage() {
  const [recipes, setRecipes] = useState<Recipe[]>([]);
  const handleLoadRecipes = async (searchText: string) => {
    const recipes = await getRecipes(searchText);
    if (recipes) {
      sessionStorage.setItem("search-text", searchText);
      sessionStorage.setItem("recipes", JSON.stringify(recipes));
      setRecipes(recipes);
      console.log(recipes);
    }
  };

  useEffect(() => {
    const recipes = JSON.parse(sessionStorage.getItem("recipes")!) as Recipe[];
    if (recipes) {
      setRecipes(recipes);
    }
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header handleLoadRecipes={handleLoadRecipes} />
      <RecipeList recipes={recipes} />
    </>
  );
}
