import Head from "next/head";
import { UIEvent, useEffect, useState } from "react";
import { Recipe } from "@/types/recipes";
import RecipeList from "@/components/RecipeList";
import Header from "@/components/Header";
import { getRecipesByHref, getRecipesBySearchWord } from "@/util/api-client";
import styles from "@/styles/HomePage.module.css";

export default function HomePage() {
  const [recipes, setRecipes] = useState<Recipe[]>([]);
  const [nextRecipes, setNextRecipes] = useState<string>("");
  const handleLoadRecipes = async (searchText: string) => {
    setNextRecipes("");
    const recipesList = await getRecipesBySearchWord(searchText);
    console.log(recipesList);
    const recipes = recipesList.hits.map((r) => r.recipe);
    if (recipes) {
      const nextRecipesLink = recipesList._links.next?.href;

      if (nextRecipesLink) {
        sessionStorage.setItem("next-recipes", nextRecipesLink);
        setNextRecipes(nextRecipesLink);
      }

      sessionStorage.setItem("search-text", searchText);
      sessionStorage.setItem("recipes", JSON.stringify(recipes));
      setRecipes(recipes);
      console.log(recipes);
    }
  };

  useEffect(() => {
    const recipes = JSON.parse(sessionStorage.getItem("recipes")!) as Recipe[];
    if (recipes) {
      setRecipes(recipes);
    }
    const nextRecipesLink = sessionStorage.getItem("next-recipes") ?? "";
    if (nextRecipesLink) {
      setNextRecipes(nextRecipesLink);
    }
  }, []);
  const loadMoreRecipes = async (href: string) => {
    if (nextRecipes) {
      const newRecipeList = await getRecipesByHref(href);

      const newRecipes = newRecipeList.hits.map((hit) => hit.recipe);
      setRecipes((prevState) => [...prevState, ...newRecipes]);

      const newRecipeLink = newRecipeList._links.next?.href;
      if (newRecipeLink) {
        setNextRecipes(newRecipeLink);
      } else {
        setNextRecipes("");
      }
    }
  };

  return (
    <>
      <Head>
        <title>Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.homeDiv}>
        <Header handleLoadRecipes={handleLoadRecipes} />
        <RecipeList
          recipes={recipes}
          loadMoreRecipes={() => loadMoreRecipes(nextRecipes)}
          hasNextRecipes={nextRecipes.length > 0}
        />
        <img className={styles.edamamBadge} src="/edamam-badge.svg" />
      </div>
    </>
  );
}
