import Head from "next/head";
import Header from "@/components/Header";
import { UserCredentials } from "@/types/user";
import { GetServerSideProps } from "next";
import styles from "@/styles/Login.module.css";
import LoginForm from "@/components/LoginForm";
import Background from "@/components/Background";

export default function Login() {
  const handleLogin = async (
    credentials: UserCredentials,
  ): Promise<Response> => {
    const headers = new Headers();
    headers.append("action", "login");
    return await fetch(`/api/users`, {
      method: "POST",
      body: JSON.stringify(credentials),
      headers: headers,
    });
  };

  return (
    <>
      <Head>
        <title>Profile Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.loginDiv}>
        <LoginForm handleLogin={handleLogin} />
      </div>
      <Background />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const { user } = req.cookies;
  if (user) {
    return {
      redirect: {
        destination: "/profile",
        permanent: false,
      },
    };
  }
  return { props: {} };
};
